name: finki-hub-analytics

networks:
  finki_stack_dev:
    driver: bridge
    name: finki_stack_dev
    # Set external to true to use an existing network
    # external: true

services:
  analytics:
    build:
      context: .
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      API_KEY: ${API_KEY}
      MONGO_URL: ${MONGO_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: finki-hub/analytics:latest
    networks:
      - finki_stack_dev
    ports:
      - "8088:8088"
    pull_policy: never
    restart: unless-stopped

  mongo:
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - mongosh
        - "--quiet"
        - "--eval"
        - db.adminCommand('ping')
      timeout: 5s
    image: mongo:8
    networks:
      - finki_stack_dev
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
